<a href="https://colab.research.google.com/github/KqkaricK/Stat/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
## HW
### HW. Блок Numpy. Задача 1

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **list_two** и присвойте ей значение сгенерированного списка случайными значениями, состоящего из **11 элементов** (должен быть тип переменной list)
- Создайте переменную **result** и присвойте ей значение переменожения **array_one** на диагональную матрицу, созданную из списка **list_two**

In [1]:
# Ваш код
import numpy as np

array_one = np.random.randint(low=-100, high=100, size=(6, 11))
list_two = np.random.randint(low=-100, high=100, size=11).tolist()
result = np.dot(array_one, np.diag(v=list_two))

print("Матрица array_one:")
print(array_one)
print("\nСпиок list_two:")
print(list_two)
print("\nПеремножение:")
print(result)


Матрица array_one:
[[ 74 -13  75  94 -61 -19  62  12 -93  -8 -78]
 [ 23  13  37 -34  76  20 -86 -25  38 -47 -12]
 [-19 -19 -34 -62  11 -79 -65 -66 -86  16  -4]
 [ 57 -72 -27 -77  13 -67  67  -3  59  57 -62]
 [-58  11 -79  96 -94   5 -36 -59  73  56  58]
 [-40  31  29  54  27  -9  48  66   8  57 -19]]

Спиок list_two:
[-2, -59, 67, -53, 29, 78, 90, -62, 79, 48, -43]

Перемножение:
[[ -148   767  5025 -4982 -1769 -1482  5580  -744 -7347  -384  3354]
 [  -46  -767  2479  1802  2204  1560 -7740  1550  3002 -2256   516]
 [   38  1121 -2278  3286   319 -6162 -5850  4092 -6794   768   172]
 [ -114  4248 -1809  4081   377 -5226  6030   186  4661  2736  2666]
 [  116  -649 -5293 -5088 -2726   390 -3240  3658  5767  2688 -2494]
 [   80 -1829  1943 -2862   783  -702  4320 -4092   632  2736   817]]


### HW. Блок Numpy. Задача 2

- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_three** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 1 столбец** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **result** и присвойте ей значение переменожения **транспонированной матрицы array_two** на матрицу **array_three**

In [2]:
# Ваш код
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
array_three = np.random.randint(low=-100, high=100, size=(11,1))
result = array_two.T @ array_three
print("Матрица array_two:")
print(array_two)
print("\nМатрица array_three:")
print(array_three)
print("\nПеремножение матриц:")
print(result)

Матрица array_two:
[[  59   55  -72  -90    4  -94    1  -22]
 [ -29   89    9   44  -87   45  -63   94]
 [ -14  -18   26  -63   76  -88   21   21]
 [ -14   19  -60   24   69   80  -99  -53]
 [  32    3  -51   14  -97  -67   62  -24]
 [  83  -65  -60  -13  -12  -64  -55   16]
 [ -96  -90 -100   42   45  -32   69   91]
 [  47  -92  -67   17  -76  -70  -35    5]
 [  30  -52    0   58   52   56   17   -1]
 [ -94   60  -18  -91    8   11    1   -4]
 [  62   65   80   52  -81   62  -68  -41]]

Матрица array_three:
[[-63]
 [ 96]
 [ 86]
 [-78]
 [ 64]
 [-94]
 [ 45]
 [-64]
 [ 67]
 [-79]
 [ 73]]

Перемножение матриц:
[[-5733]
 [ 6710]
 [21742]
 [20395]
 [-8702]
 [ 8611]
 [13996]
 [14341]]


### HW. Блок Numpy. Задача 3

- Создайте переменную **array_one** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 6 строк на 11 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_two** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Создайте переменную **array_one_t** и присвойте ей матрицу **array_one** с измененным размером, где она будет иметь 33 строки и 2 столбца (то есть, по итогу мы должны в array_one_t получить матрицу из array_one размером (33,2))
- Создайте переменную **rang_1** и присвойте ей значение найденного ранга матрицы **array_one_t** при помощи numpy
- Создайте переменную **rang_2** и присвойте ей значение найденного ранга матрицы **array_two** при помощи numpy

In [3]:
# Ваш код
array_one = np.random.randint(low=-100, high=100, size=(6, 11))
array_two = np.random.randint(low=-100, high=100, size=(11, 8))
array_one_t = np.reshape(array_one, (33, 2))
rang_1 = np.linalg.matrix_rank(array_one_t)
rang_2 = np.linalg.matrix_rank(array_two)

print("Матрица array_one:")
print(array_one)
print("\nМатрица array_two:")
print(array_two)
print("\nМатрица array_one_t:")
print(array_one_t)
print("\nранг матрицы array_one_t:")
print(rang_1)
print("\nранг матрицы array_two:")
print(rang_2)

Матрица array_one:
[[ 43 -36  77  -2  99 -55 -47  84  89  44 -56]
 [-27 -90 -86  46  57 -69  63  12 -35 -40 -72]
 [ 31  85  38  78  50  18  62  -4  10   3  69]
 [ 49 -65  98  38 -11  -2 -84 -85  91 -44  35]
 [-56 -64 -58   4 -32  42 -62  28 -11  69  30]
 [ 19 -66 -76  41  28  85 -82  53  15  11 -41]]

Матрица array_two:
[[ 59  86  80  57 -13  31  13 -16]
 [ 99 -29  53  99 -82 -46 -39 -62]
 [ 93  12  82   3  78   0 -51 -93]
 [ 61  27  10 -82  77  -7  47  78]
 [ -2  18  36  59 -74  -3  -1 -86]
 [ 25 -34 -43 -52 -71 -84  58  77]
 [-32 -79 -52 -21  81 -64 -37 -70]
 [-50  48 -32  44  10 -94 -25  99]
 [-46 -21 -32  34 -52  74  43   1]
 [ 41 -65 -41  99  27  36   8  64]
 [-89  63  86 -25 -98  82   9   6]]

Матрица array_one_t:
[[ 43 -36]
 [ 77  -2]
 [ 99 -55]
 [-47  84]
 [ 89  44]
 [-56 -27]
 [-90 -86]
 [ 46  57]
 [-69  63]
 [ 12 -35]
 [-40 -72]
 [ 31  85]
 [ 38  78]
 [ 50  18]
 [ 62  -4]
 [ 10   3]
 [ 69  49]
 [-65  98]
 [ 38 -11]
 [ -2 -84]
 [-85  91]
 [-44  35]
 [-56 -64]
 [-58   4]
 [-32 

### HW. Блок Numpy. Задача 4

- Создайте переменную **array_four** и присвойте ей значение сгенерированной матрицы случайными значениями при помощи numpy **размером 11 строк на 8 столбцов** (должен быть тип переменной numpy.ndarray)
- Получите сингулярное разложение матрицы **array_four** при помощи numpy, запишите в соответствующие переменные **U, S, Vt**, где:
    - **U** - ортогональная матрица
    - **S** - массив, числа которого используются в диагональной матрице $\Sigma$
    - **Vt** - ортогональная матрица в уже транспонированном виде (ничего транспонировать самим не нужно)
- Создайте переменную **result** и присвойте ей значение переменожения **U**, **S** и **Vt**, где от матрицы **u** необходимо взять по 8 строк и 8 столбцов (подсказка U[:8, :8]@ ....)

In [4]:
# Ваш код
array_four = np.random.randint(low=-100, high=100, size=(11, 8))
U, S, Vt = np.linalg.svd(array_four)

result = U[:8,:8] @ S @ Vt

print("Матрица array_four:")
print(array_four)
print("\nОртогональная матрица U:")
print(U)
print("\nДиагональная матрица S:")
print(np.diag(S))
print("\nОртогональная матрица Vt:")
print(Vt)
print("\nРезультат умножения U, S и Vt:")
print(result)

Матрица array_four:
[[ -31   78   76  -13   13   98   69  -21]
 [ -60   33   29  -86  -72  -30   66   79]
 [  22   -3  -42  -95   -3  -67  -75  -54]
 [ -68   65   23 -100    3  -53  -48   30]
 [ -40   -9  -68    6   97   47   22    1]
 [  87   -5   82  -53    4   73  -27   18]
 [   3   12  -85   41    1  -11   88  -14]
 [  18   67   63    0  -92  -29  -14   10]
 [ -65  -44   39  -81   14    7  -87  -55]
 [ -66   84  -85   45  -69  -69   30  -41]
 [ -71   34  -66   49  -37    8  -49   43]]

Ортогональная матрица U:
[[ 0.12122172 -0.10072075  0.54407401  0.45835779 -0.26501863 -0.48919729
  -0.05050516 -0.08734628 -0.13601869 -0.18935852 -0.30816472]
 [ 0.00926757  0.44242683  0.41605634  0.19862846  0.53586646  0.31272379
   0.22687946 -0.32844845 -0.19352401  0.09851649  0.01255853]
 [ 0.14463226  0.32078488 -0.47118854 -0.13010298  0.23516258 -0.39874273
  -0.32583543 -0.32111551 -0.35388803 -0.20303942 -0.21723327]
 [ 0.15421993  0.53378667 -0.03121064  0.33155926  0.06641174  0.0397

### HW. Блок Numpy. Задача 5

- Вам дана матрица **X_matrix** ниже (скопируйте код и вставьте в code editor)
- Необходимо вычислить собственные векторы и собственные значения матрицы **X_matrix** при помощи numpy:
    - Создайте перменную **w** и присвойте ей массив с собственными значениями матрицы X_matrix (тип numpy.ndarray)
    - Создайте перменную **v** и присвойте ей матрицу с собственными векторами матрицы X_matrix (тип numpy.ndarray)
- Проверьте, что при умножении матрицы X_matrix и собственного вектора, получается тот же результат, что и при умножении собственного значения и собственного вектора, для этого:
    - Создайте переменную **check_1** и присвойте ей результат перемножения матрицы X_matrix на нулевой вектор из **v**
    - Создайте переменную **check_2** и присвойте ей результат перемножения нулевого вектора **v** на собственное значение **w** под индексом 0
    
**Подсказка:**

Получившийся результат в **check_1** должен быть равен **check_2**

In [5]:
X_matrix = np.array([[-1, -6], [2, 6]])

# Ваш код
w, v = np.linalg.eig(X_matrix)

check_1 = X_matrix @ v[:, 0]
check_2 = w[0] * v[:, 0]

print("Собственные значения w:")
print(w)
print("\nСобственные векторы v:")
print(v)
print("\nРезультат умножения X_matrix на собственный вектор:")
print(check_1)
print("\nРезультат умножения собственного значения на собственный вектор:")
print(check_2)

Собственные значения w:
[2. 3.]

Собственные векторы v:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]

Результат умножения X_matrix на собственный вектор:
[-1.78885438  0.89442719]

Результат умножения собственного значения на собственный вектор:
[-1.78885438  0.89442719]


### HW. Блок Numpy. Задача 6

- Вам даны два вектора **a** и **b** ниже (скопируйте код и вставьте в code editor)
- Создайте переменную **similarity** и присвойте значение косинуса угла между векторами **a** и **b** (можно использовать scipy)
- найдите длины векторов:
    - Создайте переменную **dist_a_manh** и присвойте значение Манхэттенской нормы вектора **a**
    - Создайте переменную **dist_b_manh** и присвойте значение Манхэттенской нормы вектора **b**
    - Создайте переменную **dist_a_euclid** и присвойте значение Евклидовой нормы вектора **a**
    - Создайте переменную **dist_b_euclid** и присвойте значение Евклидовой нормы вектора **b**

In [6]:
a = np.array([2, 4, 5])
b = np.array([1, 3, 2])

# Ваш код
from scipy.spatial.distance import cosine

similarity = 1 - cosine(a, b)
dist_a_manh = np.linalg.norm(a, ord=1)
dist_b_manh = np.linalg.norm(b, ord=1)
dist_a_euclid = np.linalg.norm(a, ord=2)
dist_b_euclid = np.linalg.norm(b, ord=2)

print("Косинус угла между векторами a и b:")
print(similarity)
print("\nМанхэттенская норма вектора a:")
print(dist_a_manh)
print("\nМанхэттенская норма вектора b")
print(dist_a_manh)
print("\nЕвклидова норма вектора a")
print(dist_a_euclid)
print("\nЕвклидова норма вектора b")
print(dist_b_euclid)



Косинус угла между векторами a и b:
0.9561828874675149

Манхэттенская норма вектора a:
11.0

Манхэттенская норма вектора b
11.0

Евклидова норма вектора a
6.708203932499369

Евклидова норма вектора b
3.7416573867739413
